Human readable command error messages
Before we showed the actual Roc type of the error like

```
kai build

Program exited with error: PlanningFailed({ backend: "nix", command:
"build", location: None, message: "build requires exactly one config
name", plugin: "std" })
```

Now we have the much more human friendly:

```
kai build

error: build requires exactly one artifact argument
usage: kai build <ARTIFACT>
example: kai build <my-artifact>
```